### ISSUE TITLE
Culture Order

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/hl7-be-fhir-laboratory-report#117]
@JoostAtMips @JoostVanAverbeke @thibaultmh Can you explain a bit?

**Comment by bdc-ehealth** [comment]
MIPS would like to introduce an observation for cultures which contains the isolation observations. Now the guidance states that the isolation observations should be directly in the report. Do we want to change this?

**Comment by thibaultmh** [comment]
This guidance should change. We will not put the organism observation under the report. Instead we will introduce a culture observation that has organism observations as members. 

This was doen because a report can have multiple cultures and we couldn't distinguish between the multiple cultures.

![afbeelding](https://user-images.githubusercontent.com/86883419/163173301-277a466f-f6e6-4a73-a1af-555b7de348db.png)

**Comment by bdc-ehealth** [comment]
The WG accepts this way of working. (Remaining issues will be discussed between Philippe Cauchie and MIPS)
